name: sde-a6000
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.10.14
  - certifi=2020.11.8
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.7.9
  - readline=8.0
  - setuptools=50.3.1
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.11.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cachetools==4.1.1
    - cffi==1.14.4
    - chardet==3.0.4
    - click==7.1.2
    - configparser==5.0.1
    - cycler==0.10.0
    - dataclasses==0.6
    - decorator==4.4.2
    - defusedxml==0.6.0
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - fsspec==0.8.4
    - future==0.18.2
    - gitdb==4.0.5
    - gitpython==3.1.11
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.33.2
    - idna==2.10
    - importlib-metadata==3.1.0
    - ipdb==0.13.4
    - ipykernel==5.4.2
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.5
    - numpy==1.19.4
    - oauthlib==3.1.0
    - packaging==20.8
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.1
    - prometheus-client==0.9.0
    - promise==2.3
    - prompt-toolkit==3.0.8
    - protobuf==3.14.0
    - psutil==5.7.3
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.7.3
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytorch-lightning==1.0.8
    - pytz==2020.4
    - pyyaml==5.3.1
    - pyzmq==20.0.0
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.5.4
    - seaborn==0.11.0
    - send2trash==1.5.0
    - sentry-sdk==0.19.4
    - shortuuid==1.0.1
    - six==1.15.0
    - smmap==3.0.4
    - subprocess32==3.5.4
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - terminado==0.9.1
    - testpath==0.4.4
    - torch==1.7.0
    - torchvision==0.8.1
    - tornado==6.1
    - tqdm==4.54.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - wandb==0.10.11
    - watchdog==0.10.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - zipp==3.4.0
